name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          ssh $SERVER_USER@$SERVER_IP << 'ENDSSH'
          # NVM 초기화
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          
          # Node.js 버전 확인 및 설정
          nvm use 18 || nvm install 18
          
          # 전역 패키지 설치
          npm install -g yarn pm2
          
          # 애플리케이션 배포
          cd ~/travel-duo-server
          git pull origin main
          yarn
          npm run build
          pm2 restart travel-duo-server || pm2 start npm --name "travel-duo-server" -- start:prod
          ENDSSH
